seed_everything: 42

model:
  class_path: models.clat.CLAT
  init_args:
    arch_name: cait_xs24_384_concept
    pretrained: true
    disease_loss_weight: 1.0
    lesion_loss_weight: 0.6
    KG_loss_weight: 0.4
    with_EK: true
    training_int_prob: 0.25
    training_int_milestone: 10

optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 4e-5
    weight_decay: 1e-4

lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  init_args:
    T_0: 10
    T_mult: 2
    eta_min: 1e-6

trainer:
  devices: [0,]
  max_epochs: 200
  log_every_n_steps: 1
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: logs
      name: .test
      version: 
      log_graph: false
      default_hp_metric: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/kappa
        mode: max
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: loss/val_loss
        mode: min
        patience: 15
        verbose: true
    - class_path: callbacks.MetricsCaculator
      init_args:
        verbose: true